---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: credentials
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: 
    {{- $existingSecret := lookup "v1" "Secret" $.Values.namespace "credentials" -}}
    {{- if not (and $existingSecret (hasKey $existingSecret.data "GF_SECURITY_ADMIN_PASSWORD")) }}
      {{ randAlphaNum 48 | b64enc }}
    {{- end }}
 
  INFLUX_DB_FLUX_TOKEN: 
     {{- if not (and $existingSecret (hasKey $existingSecret.data "INFLUX_DB_FLUX_TOKEN")) }}
      {{ randAlphaNum 48 | b64enc }}
    {{- end }}
  
  INFLUX_TOKEN: 
    {{- if not (and $existingSecret (hasKey $existingSecret.data "INFLUX_TOKEN")) }}
      {{ randAlphaNum 48 | b64enc }}
    {{- end }}
 
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.namespace }}
  name: seeds
type: Opaque
stringData:
{{- range $.Values.inputs }}
{{ .short_name | upper | indent 2 }}_SEED: {{ .network_monitor_seed | quote }}
{{- end }}
---
apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: Secret
metadata:
  name: {{ .Values.ecr.generatedSecretName }}
  namespace: {{ $.Values.namespace }}
spec:
  ecr_registry: {{ .Values.ecr.registry }}
  frequency: {{ .Values.ecr.frequency }}
  generated_secret_name: {{ .Values.ecr.generatedSecretName }}
  region: {{ .Values.ecr.region }}
